### ISSUE TITLE
Package Microsoft.ProgramSynthesis 2.3.0 is not compatible with uap10.0.10586

### ISSUE THREAD

**Issue by evalgor** [Microsoft/prose#12]
Hello,
I tried to install Prose on my freshly installed Visual Studion using NUGET console. After executing:
`Install-Package Microsoft.ProgramSynthesis`
I get:
```
Install-Package : Package Microsoft.ProgramSynthesis 2.3.0 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586). Package Microsoft.ProgramSynthesis 2.3.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.6 (.NETStandard,Version=v1.6)
At line:1 char:1
+ Install-Package Microsoft.ProgramSynthesis
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Please help to resolve this issue.

**Comment by danpere** [comment]
I'm not sure I'm understanding what's going on correctly, but that error message seems to imply you've created your project as a Universal Windows Platform application, which I believe is for making applications for the Windows 10 store. PROSE only supports the desktop .NET framework ("Classic Desktop" or "Windows Classic Desktop" on the Visual Studio dialogs I'm seeing) and .NET Core.

You may also need to follow the instructions in [this comment](https://github.com/Microsoft/prose/issues/11#issuecomment-307295094) in order to be able to actually add the package at the moment.
