### ISSUE TITLE
System.NullRefenceException in FlashFill Example

### ISSUE THREAD

**Issue by Mestway** [Microsoft/prose#5]
When I'm running the FlashFill example in the SDK, I encountered an "System.NullRefenceException" for a learning example.

Code snippet:

```
var examples = new[]
   {
        new FlashFillExample(new FlashFillInput("c", "a", "k"), "c a. k"),
        new FlashFillExample(new FlashFillInput("a", "", "c"), "a c"),
        new FlashFillExample(new FlashFillInput("a", "j", "i"), "a j. i"),
        new FlashFillExample(new FlashFillInput("a", "", "i"), "a i"),
        new FlashFillExample(new FlashFillInput("x", "y", "i"), "x y. i")
    };
FlashFillProgram program = FlashFillProgram.Learn(examples);
string output = program.Run("a", "x", "i");
```

I run the code and there is a System.NullRefenceException on the last line of the code. Besides, if I only set examples containing only one instance (e.g.  first instance of the example list), I won't get the Exception.

What is the cause and how can I handle it?

Thanks!

**Comment by danpere** [comment]
`FlashFillProgram.Learn()` returns `null` when it is unable to learn a program. In this case, the program you want to learn is not expressible in the FlashFill language, so it returns `null`. As you noticed, any one example does work because the program is expressible as two branches (in your list, the odd and even examples), each of which is separately expressible as a FlashFill program. But the entire semantics cannot be expressed in a single program due to the lack of support for conditionals in this implementation of FlashFill.

**Comment by Mestway** [comment]
I see, however, the problem is not that `null` is returned, but an unhandled exception appeared. That might be not be what you are aware of.

Thanks!

**Comment by danpere** [comment]
The exception is in your code. Whenever you call `FlashFillProgram.Learn()`, you need to check if the result is `null`.
