### ISSUE TITLE
Add `CONTRIBUTING.md` and .`github` with PR and Issue Template

### ISSUE THREAD

**Issue by Haleshot** [microsoft/prose#79]
Hi maintainers,

Wanted to ask if you guys would like contributions for the repository such as
- `CONTRIBUTING.md`
- `.github` folders containing PR and Issue templates.

Thought it would help in maintaining uniformity across PRs (during review); also help in `open-source` standards.

**Comment by simmdan** [comment]
Thanks for the offer, but as it turns out, the purpose of this repository is not very conducive to contributions.  It's not that we are opposed to contributions, but the repository contains mostly release notes and samples for how to use our closed-source library which is not part of the repository.  So, we don't get or expect many contributions.

**Comment by Haleshot** [comment]
> Thanks for the offer, but as it turns out, the purpose of this repository is not very conducive to contributions. It's not that we are opposed to contributions, but the repository contains mostly release notes and samples for how to use our closed-source library which is not part of the repository. So, we don't get or expect many contributions.

Understood; thanks for the response.
